/** Fixed, reachable offline tactical comparisons. Host state never enters policy inputs. */
import assert from 'node:assert/strict';
import { writeFileSync, mkdirSync } from 'node:fs';
import { gzipSync } from 'node:zlib';
import { createReferee } from '../referee.ts';
import { transition } from '../internal/reducer.ts';
import { playerView } from '../internal/view.ts';
import { simulationSeed } from '../simulation/index.ts';
import { auditPolicy } from './bots.ts';
import { checkView, checkState, checkTransition, suit, winner } from './validation-invariants.ts';
import { profiles } from './validation.ts';
import type { Lineup, Profile } from './validation.ts';
import type { State } from '../internal/state.ts';
import type { Action, Seat, Suit, PlayerView, HandResult } from '../types.ts';
const seats=[0,1,2,3] as const,suits:Suit[]=['clubs','diamonds','hearts','spades'];
export function lonerFixtures(){const records=[];const bot=auditPolicy('strong-balanced');for(const dealer of seats)for(const caller of seats)for(const round of [1,2])for(let sample=0;sample<4;sample++){const seed=simulationSeed(90192026,sample),ref=createReferee({seed,dealer}),trace:Array<{seat:Seat;action:Action}>=[];let s=ref.snapshot(),openingLeader:Seat|null=null;checkState(s);while(!s.result){const seat=s.turn!,v=ref.player(seat).view();checkView(s,v);let action:Action;if(s.phase==='bidding')action=s.biddingRound===round&&seat===caller?(round===1?{type:'order-up',alone:true}:{type:'call',suit:suits.find(t=>t!==s.upCard.split(':')[0])!,alone:true}):{type:'pass'};else action=bot(v);if(s.phase==='playing'&&openingLeader===null)openingLeader=seat;trace.push({seat,action});assert.ok(trace.length<=30);assert.ok(ref.player(seat).act(action).ok);const after=ref.snapshot();checkTransition(s,action,after);s=after;}assert.equal(s.alone,true);assert.equal(s.caller,caller);assert.equal(trace.filter(x=>x.action.type==='play').length,15);records.push({seed,dealer,caller,round,result:s.result,openingLeader,plays:15,trace});}return records;}
interface Choice{profile:Profile;action:Action;outcome:{net:number;result:HandResult};}
interface Observation{seed:number;dealer:Seat;block:number;hand:number;decision:number;contexts:string[];view:PlayerView;choices:Choice[];}
function rollout(start:State,action:Action,lineup:Lineup){const team=start.turn!%2;let s=start,count=0;const bots=lineup.map(auditPolicy);while(!s.result){const v=playerView(s,s.turn!);checkView(s,v);const a=count===0?action:bots[s.turn!]!(v),after=transition(s,s.turn!,a);assert.ok(after);checkTransition(s,a,after);s=after;assert.ok(++count<=29,'Remaining bidding/discard/play bound');}return {net:s.result.team===team?s.result.points:-s.result.points,result:s.result};}
export function tacticalComparisons(){const lineup:Lineup=['strong-balanced','strong-assertive','val','strong-conservative'],candidates:Profile[]=['val',...profiles('strong')],bots=lineup.map(auditPolicy),observations:Observation[]=[],games=[];for(let block=0;block<32;block++){const seed=simulationSeed(90252026,block),dealer=(block%4) as Seat,ref=createReferee({seed,dealer});let s=ref.snapshot(),decision=0;const selected:Record<string,number>={};checkState(s);while(s.phase!=='game-over'){if(s.result){ref.nextHand();s=ref.snapshot();checkState(s);}const seat=s.turn!,v=ref.player(seat).view();checkView(s,v);const contexts:string[]=[];if(s.phase==='bidding')contexts.push('bidding');if(s.phase==='playing'&&v.legalActions.length>=2){if(!s.trick.length){contexts.push('lead');if(s.completedTricks.some(t=>t.plays[0]!.seat===(seat+2)%4&&t.winner%2===seat%2))contexts.push('partner-return');}else if(winner(s.trick,s.trump!)===(seat+2)%4)contexts.push('partner-winning');if(v.hand.some(c=>suit(c,s.trump!)===s.trump))contexts.push('trump-conservation');}const keep=contexts.filter(k=>(selected[k]??0)<2);if(keep.length){keep.forEach(k=>{selected[k]=(selected[k]??0)+1;});observations.push({seed,dealer,block,hand:s.handNumber,decision,contexts:keep,view:v,choices:candidates.map(profile=>{const action=auditPolicy(profile)(v);return {profile,action,outcome:rollout(s,action,lineup)};})});}const action=bots[seat]!(v);assert.ok(ref.player(seat).act(action).ok);const after=ref.snapshot();checkTransition(s,action,after);s=after;assert.ok(++decision<=2000);}games.push({seed,dealer,block,score:s.score,winner:s.winner,hands:s.handNumber,decisions:decision,selected});}return {lineup,games,observations};}
if(process.argv.includes('--run')){mkdirSync('reports/bot-validation',{recursive:true});const start=performance.now(),loners=lonerFixtures(),tactical=tacticalComparisons();writeFileSync('reports/bot-validation/fixtures.json.gz',gzipSync(JSON.stringify({version:'v2-reconstruction',loners,tactical,seconds:(performance.now()-start)/1000})));console.log(JSON.stringify({lonerHands:loners.length,lonerOutcomes:loners.reduce<Record<string,number>>((a,r)=>{a[r.result.reason]=(a[r.result.reason]??0)+1;return a;},{}),tacticalGames:tactical.games.length,views:tactical.observations.length,contexts:tactical.observations.flatMap(x=>x.contexts).reduce<Record<string,number>>((a,k)=>{a[k]=(a[k]??0)+1;return a;},{}),seconds:(performance.now()-start)/1000}));}
