/** On-demand offline audit. No imports from browser or collection code. */
import { createHash } from 'node:crypto';
import { cpus } from 'node:os';
import { readFileSync, writeFileSync, existsSync, mkdirSync, renameSync } from 'node:fs';
import { gzipSync, gunzipSync } from 'node:zlib';
import { spawn } from 'node:child_process';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
import { VERSION, design, checkMatched, runValidationGame } from './validation.ts';
import type { Case, Game } from './validation.ts';
import { OPPONENT_PROFILES } from '../bots/profiles.ts';
import { simulationSeed } from '../simulation/index.ts';
export const ALLOCATION={casual:128,expert:64,cross:32,val:16,strong:320,symmetry:32};
export interface Job{id:string;category:string;group:string;base:number;start:number;count:number;cases:Case[];}
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
export function jobs():Job[]{const out:Job[]=[];for(const [category,n] of Object.entries(ALLOCATION)){const cases=design(category);for(const group of new Set(cases.map(c=>c.group)))for(let start=0;start<n;start+=8)out.push({id:`${category}-${hash(group).slice(0,10)}-${start}`,category,group,base:parseInt(hash(`20260925-validation-v1:${group}`).slice(0,8),16),start,count:8,cases:cases.filter(c=>c.group===group)});}return out.sort((a,b)=>a.start-b.start||Object.keys(ALLOCATION).indexOf(a.category)-Object.keys(ALLOCATION).indexOf(b.category));}
export interface Chunk{jobId:string;base:number;group:string;category:string;seconds:number;matchedHands:number;unmatchedTailHands:number;games:Game[];}
export function validateChunk(j:Job,c:Chunk){assert.equal(c.jobId,j.id);assert.equal(c.base,j.base);assert.equal(c.category,j.category);assert.equal(c.group,j.group);assert.equal(c.games.length,j.count*j.cases.length);const keys=new Set<string>();let matchedHands=0,unmatchedTailHands=0;for(let b=j.start;b<j.start+j.count;b++){const games=c.games.filter(g=>g.block===b);assert.equal(games.length,j.cases.length);for(const g of games){const config=j.cases.find(c=>c.id===g.caseId);assert.ok(config);const key=`${g.caseId}/${b}`;assert.ok(!keys.has(key));keys.add(key);assert.equal(g.seed,simulationSeed(j.base,b));assert.equal(g.dealer,(b+config.rotation)%4);assert.deepEqual(g.lineup,config.lineup);assert.equal(g.score[g.winner]!>=10,true);const scores=[0,0];g.hands.forEach((h,i)=>{assert.equal(h.number,i+1);assert.equal(h.dealer,(g.dealer+i)%4);scores[h.result.team]!+=h.result.points;assert.equal(h.bids.filter(x=>x.action==='call').length,1);assert.equal(h.bids.at(-1)!.seat,h.caller);assert.equal(h.bids.at(-1)!.forced,h.bids.length===8);});assert.deepEqual(scores,g.score);}const m=checkMatched(games);matchedHands+=m.matchedHands;unmatchedTailHands+=m.unmatchedTailHands;}assert.equal(c.matchedHands,matchedHands);assert.equal(c.unmatchedTailHands,unmatchedTailHands);}
function arg(name:string,fallback:string){const i=process.argv.indexOf(name);return i<0?fallback:process.argv[i+1]!;}
const root=arg('--output','reports/bot-validation');
function save(path:string,obj:unknown,gz=false){const tmp=path+'.tmp';writeFileSync(tmp,gz?gzipSync(JSON.stringify(obj)):JSON.stringify(obj,null,2)+'\n');renameSync(tmp,path);}
async function main(){mkdirSync(`${root}/detailed`,{recursive:true});mkdirSync(`${root}/failures`,{recursive:true});const schedule=jobs(),mode=arg('--mode','run');
 if(mode==='manifest'){assert.ok(!existsSync(`${root}/manifest.json`),'Refusing to overwrite fixed manifest');save(`${root}/manifest.json`,{version:VERSION,sourceCommit:'46e4a0c04f9007387bc98ef4aaf1d256f20aec05',reconstructionCommit:'a56df2459e5b2c21c7f70c839430483df0be729a',created:new Date().toISOString(),seedNamespace:'20260925-validation-v1:',allocation:ALLOCATION,profiles:OPPONENT_PROFILES,expectedGames:schedule.reduce((n,j)=>n+j.count*j.cases.length,0),jobs:schedule,bootstrap:{resamples:1999,primaryComparisons:16,seatPracticalMargin:0.02,winPracticalMargin:0.05,scorePracticalMargin:0.5},recovery:{retainedChunks:82,retainedGames:7584,rerunChunks:254,rerunGames:33440,reason:'Original executor reset; unchanged deterministic schedule reconstructed and replay checked'}});console.log('Manifest saved',schedule.length);return;}
 if(mode==='benchmark'){const results=[];for(const category of ['strong','expert']){const start=performance.now(),games=Array.from({length:8},(_,i)=>runValidationGame(design(category)[0]!,i,82992026));results.push({category,games:8,hands:games.reduce((n,g)=>n+g.hands.length,0),seconds:(performance.now()-start)/1000,policyMs:games.flatMap(g=>g.policyMs).reduce((a,b)=>a+b,0)});}save(`${root}/benchmark-reconstruction.json`,{node:process.version,cpu:cpus()[0]?.model,results});console.log(JSON.stringify(results));return;}
 const manifest=JSON.parse(readFileSync(`${root}/manifest.json`,'utf8'));assert.deepEqual(manifest.jobs,schedule,'Schedule drift');
 if(mode==='worker'){const job=schedule.find(j=>j.id===arg('--job',''));assert.ok(job);const start=performance.now(),games:Game[]=[];let matchedHands=0,unmatchedTailHands=0;try{for(let b=job.start;b<job.start+job.count;b++){const block=job.cases.map(c=>runValidationGame(c,b,job.base));const m=checkMatched(block);matchedHands+=m.matchedHands;unmatchedTailHands+=m.unmatchedTailHands;games.push(...block);}const chunk={jobId:job.id,base:job.base,group:job.group,category:job.category,seconds:(performance.now()-start)/1000,matchedHands,unmatchedTailHands,games};validateChunk(job,chunk);save(`${root}/detailed/${job.id}.json.gz`,chunk,true);}catch(e){save(`${root}/failures/${job.id}.json`,{job,error:String(e)});throw e;}return;}
 assert.equal(mode,'run');const workers=Number(arg('--workers','4'));assert.ok(Number.isInteger(workers)&&workers>=1&&workers<=8);let retained=0;const pending=schedule.filter(j=>{const p=`${root}/detailed/${j.id}.json.gz`;if(!existsSync(p))return true;validateChunk(j,JSON.parse(gunzipSync(readFileSync(p)).toString()));retained++;return false;}).slice(0,Number(arg('--max-jobs','99999')));console.log(JSON.stringify({retained,pending:pending.length,workers}));let index=0,completed=0,failed=0;const start=performance.now();await Promise.all(Array.from({length:workers},async()=>{while(index<pending.length){const j=pending[index++]!;const code=await new Promise<number>(resolve=>{const child=spawn(process.execPath,[fileURLToPath(import.meta.url),'--mode','worker','--job',j.id,'--output',root],{stdio:['ignore','ignore','pipe']});let err='';child.stderr.on('data',b=>{err+=String(b);});child.on('error',e=>{err+=String(e);});child.on('close',code=>{if(code!==0)writeFileSync(`${root}/failures/${j.id}.stderr.txt`,err);resolve(code??1);});});if(code)failed++;else completed++;console.log(JSON.stringify({job:j.id,completed,failed,remaining:pending.length-completed-failed,seconds:(performance.now()-start)/1000}));}}));save(`${root}/run-last.json`,{version:VERSION,retained,completed,failed,seconds:(performance.now()-start)/1000,workers,date:new Date().toISOString()});if(failed)process.exitCode=1;
}
if(process.argv[1]===fileURLToPath(import.meta.url))await main();
