import { readFile, writeFile, mkdir, copyFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';
import type { NarrationClip } from '../web/narration-types.ts';
import { wholeEventContract, acceptedAlternatives } from './narrator-whole-contract.ts';

type VerifiedClip = NarrationClip & { decodeVerified: boolean };
const [source, sampleSource] = process.argv.slice(2);
if (!source || !sampleSource) throw new Error('Usage: node scripts/import-narrator-whole-pack.ts /path/to/stage-one /path/to/accepted-repair-pack');
const pack = JSON.parse(await readFile(path.join(source, 'manifest.json'), 'utf8')) as { clips: Record<string, VerifiedClip> };
const samples = JSON.parse(await readFile(path.join(sampleSource, 'samples/manifest.json'), 'utf8')) as { clips: Record<string, VerifiedClip> };
const expected = wholeEventContract();
if (Object.keys(pack.clips).length !== 379 || Object.keys(expected).length !== 379) throw new Error('Expected all 379 canonical stage-one recordings');
const runtime: Record<string, NarrationClip> = {};
const copies: Array<{ source: string; destination: string }> = [];
for (const [id, text] of Object.entries({ ...expected, ...acceptedAlternatives })) {
  const alternative = id in acceptedAlternatives;
  const clip = (alternative ? samples : pack).clips[id];
  const inputUrl = alternative ? `samples/${id}.mp3` : `audio/${id}.mp3`;
  if (!clip || clip.id !== id || clip.text !== text || clip.status !== 'ready' || !clip.decodeVerified || clip.url !== inputUrl) throw new Error(`Missing or unverified whole-event recording ${id}`);
  const input = path.join(alternative ? sampleSource : source, clip.url);
  const bytes = await readFile(input);
  if (bytes.length !== clip.bytes || createHash('sha256').update(bytes).digest('hex') !== clip.sha256) throw new Error(`Integrity failure ${id}`);
  if (!Number.isFinite(clip.durationSeconds) || clip.durationSeconds <= 0) throw new Error(`Invalid duration ${id}`);
  const url = `audio/${id}.mp3`;
  runtime[id] = { id, url, text, status: clip.status, durationSeconds: clip.durationSeconds, sha256: clip.sha256, bytes: clip.bytes };
  copies.push({ source: input, destination: path.join('web', url) });
}
// No partial import: every required file above is checked before any write.
await mkdir('web/audio', { recursive: true });
for (const copy of copies) await copyFile(copy.source, copy.destination);
await writeFile('web/narrator-whole-manifest.ts', "import type { NarrationManifest } from './narration-types.ts';\n// Generated by scripts/import-narrator-whole-pack.ts from verified complete assets.\nexport const narratorWholeManifest: NarrationManifest = " + JSON.stringify(runtime, null, 2) + ';\n');
await mkdir('docs/narrator-preview', { recursive: true });
await copyFile(path.join(source, 'manifest.json'), 'docs/narrator-preview/whole-stage-one-manifest.json');
await writeFile('docs/narrator-preview/accepted-whole-alternatives.json', JSON.stringify({ ...samples, clips: Object.fromEntries(Object.keys(acceptedAlternatives).map(id => [id, samples.clips[id]])) }, null, 2) + '\n');
console.log(`Imported 379 complete canonical sentences and 2 accepted alternatives (${Object.values(runtime).reduce((sum, clip) => sum + clip.bytes, 0)} bytes).`);
