import { readFile, writeFile, mkdir, copyFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';
import type { NarrationClip } from '../web/narration-types.ts';

const source = process.argv[2];
if (!source) throw new Error('Usage: node scripts/import-narrator-pack.ts /path/to/verified/pack');
const pack = JSON.parse(await readFile(path.join(source, 'manifest.json'), 'utf8')) as { clips: Record<string, NarrationClip & { decodeVerified: boolean }> };
const entries = Object.entries(pack.clips);
if (entries.length !== 127) throw new Error(`Expected the agreed 127 entries, got ${entries.length}`);
const runtime: Record<string, NarrationClip> = {};
await mkdir('web/audio', {recursive: true});
for (const [id, clip] of entries) {
  if (clip.id !== id || clip.status !== 'ready' || !clip.decodeVerified || !/^audio\/[a-z0-9.-]+\.mp3$/.test(clip.url)) throw new Error(`Unverified clip ${id}`);
  const bytes = await readFile(path.join(source, clip.url));
  if (bytes.length !== clip.bytes || createHash('sha256').update(bytes).digest('hex') !== clip.sha256) throw new Error(`Integrity failure ${id}`);
  if (!Number.isFinite(clip.durationSeconds) || clip.durationSeconds <= 0) throw new Error(`Invalid duration ${id}`);
  await copyFile(path.join(source, clip.url), path.join('web', clip.url));
  const {url, text, status, durationSeconds, sha256} = clip;
  runtime[id] = {id, url, text, status, durationSeconds, sha256, bytes: clip.bytes};
}
await writeFile('web/narrator-manifest.ts', "import type { NarrationManifest } from './narration-types.ts';\n// Generated by scripts/import-narrator-pack.ts from checksum/decode-verified assets.\nexport const narratorManifest: NarrationManifest = " + JSON.stringify(runtime, null, 2) + ';\n');
await mkdir('docs/narrator-preview', {recursive: true});
await copyFile(path.join(source, 'manifest.json'), 'docs/narrator-preview/voice-pack-manifest.json');
console.log(`Imported ${entries.length} verified clips, ${entries.reduce((sum, [, clip])=>sum+clip.bytes, 0)} bytes.`);
