"""Render readable conclusions and explicit-denominator appendices from recomputed evidence."""
from pathlib import Path
import json,gzip,hashlib,platform,subprocess
from collections import Counter
ROOT=Path(__file__).resolve().parents[1];O=ROOT/'reports/bot-validation';D=ROOT/'docs/audits/bot-validation'
s=json.loads((O/'summary.json').read_text());t=json.loads((O/'tactical-summary.json').read_text());m=json.loads((O/'manifest.json').read_text())
def estimate(x,scale=100,adjusted=False):
 ci=x.get('familyWise95' if adjusted else 'ci95');e=x['estimate'];v='unavailable' if e is None else f'{e*scale:+.2f}'
 return v+'; 95% interval '+('unavailable' if ci is None else f'[{ci[0]*scale:+.2f}, {ci[1]*scale:+.2f}]')+f"; {x['blocks']} independent blocks"+('; sparse' if x['sparse'] else '')
def pairtext(key):
 return '\n'.join(f"{kind}: win {estimate(s[kind][key]['win'])} percentage points; score {estimate(s[kind][key]['score'],1)} points." for kind in ['teams','common'])
lines=[]
lines.append('Euchre bot validation and calibration — completed recovery, September 25, 2026 UTC\n')
lines.append('No live engine or bot-policy defect was confirmed. All 41,024 scheduled games are now backed by retained per-game evidence. The lost portion was regenerated using the same fixed seeds and assignments. All category game, hand and decision totals and all 26 primary point estimates exactly match the surviving original analysis. No strategy parameters or production behavior were changed.\n')
lines.append('No meaningful right-seat voluntary-calling advantage was established. Several intervals remain too wide to rule out the predeclared two-percentage-point margin. An exploratory lower right-seat call-success signal remains in one Strong comparison; its mechanism is unresolved.\n')
lines.append('The pooled evidence supports Casual < Strong < Expert for both same-tier teams and common-partner substitutions. Individual matchup uncertainty remains. Val is practically similar to Balanced and Partnership Strong in the tested pooled contexts. Its small apparent deficit to Assertive Strong is not robust to the primary multiple-comparison adjustment.\n')
lines.append('No confirmed live defect from this battery blocks PR #8 acceptance. The audit itself is complete; device and VoiceOver acceptance remain outside its scope. Nothing was merged. No simulation entered the human ledger.\n')
lines.append('Recovery and provenance\n')
lines.append('The initial PR #8 SHA matched 46e4a0c04f9007387bc98ef4aaf1d256f20aec05. Main remains b6f647c7d64c58e7b147cb03df729433604d3650; PR #7 remains fba6aa22acffb20c27f7f0e2a35a4980d4227082. Only the existing PR #8 branch received audit changes.\n')
lines.append('A prior executor reset lost unpublished harness files and 254 detailed batches. The 82 recovered batches (7,584 games) were retained byte for byte. The other 254 batches (33,440 games) were rerun, without adding or selecting seeds. Primary point estimates are unchanged. Pooled reconstructed intervals use a documented sorted-stratum bootstrap and can differ slightly from the preserved original intervals. The reconstructed driver exactly replays a retained game’s permitted decisions, deal signatures, scores and trace digest. Source and fixed manifest were published before recovery runs. Results were checkpointed between bounded waves. Historical partial-recovery files remain explicitly labeled.\n')
lines.append(f"There are {s['independentBlocks']:,} independent group/seed blocks, {s['matchedHands']:,} matching-hand fingerprint comparisons and {s['unmatchedTailHands']:,} hand occurrences beyond their block’s shortest game. No deal mismatches occurred. Complete games may end at different hands; complete-game outcomes retain tails, while the separate common-prefix analysis is an outcome-dependent sensitivity check.\n")
lines.append('The predeclared practical margins are 2 percentage points for voluntary calls, 5 percentage points for win differences, and 0.5 final-score points. Every bootstrap retains whole matched blocks; pooled cross-tier and Val comparisons resample within fixed lineup contexts. There are 1,999 deterministic resamples. Ordinary 95% intervals appear below; family-wise intervals for 16 primary comparisons appear in summary.json and COMPARISONS.txt. Subgroups are exploratory. Nonsignificance does not establish equivalence.\n')
lines.append('Actual coverage\n')
for cat,v in s['coverage'].items():lines.append(f"{cat}: {v['games']:,} games, {v['hands']:,} hands, {v['decisions']:,} decisions, {v['cases']} cases, {v['blocks']} independent blocks; {m['allocation'][cat]} games per case.\n")
lines.append('Total: 41,024 complete games, 462,717 hands and 11,640,424 decisions. The schedule covers every category before expanding its predetermined blocks. Four processes ran at most concurrently. Recovery wave runtimes are in run-wave*.json; per-batch costs are in the detailed records. Cached batches retain their original timings, so the sum is not one contiguous wall-clock measurement.\n')
for cat,title in [('casual','Casual profiles and seats'),('expert','Expert profiles and seats'),('strong','Independent Strong replication')]:
 lines.append(title+'\n')
 lines.append('Every same-profile control and distinct ordered profile pair ran with both the original seat-zero proxy/Val placement and those opposing players exchanged. Initial dealers were balanced. Relative dealer position, absolute seat, profile, partner and opposing identities remain distinct.\n')
 for variant in ['original','proxy-swapped']:
  row=s['seat'][f'{cat}/{variant}/all/full'];lines.append(f"{variant}, right minus left: voluntary call rate {estimate(row['voluntary_call_rate'])} percentage points; call make rate {estimate(row['make_rate'])} percentage points; net points per call {estimate(row['net_points_per_call'],1)}.\n")
 for k,row in s['profileContrasts'].items():
  if k.startswith(cat+'/original/'):lines.append(k.split('/')[-1]+': voluntary call difference '+estimate(row)+' percentage points. This describes bidding behavior, not a strength ranking.\n')
 if cat=='expert':lines.append('Expert retained its real 24-sample, three-card search budget. The 64 blocks leave wide seat intervals; the two-point seat margin is unresolved. benchmark-reconstruction.json records eight games per audited Strong/Expert lineup, with the exact lineup, elapsed time and policy time. Val occupies seat two in those benchmark cases; these are not four-Expert-versus-four-Strong team benchmarks. Per-profile policy cost is recorded separately from playing strength.\n')
 if cat=='strong':
  lines.append('The 320 fresh blocks comprise two predetermined 160-block batches, exceeding the previous 250 games/case. All 320 new seeds were checked against both original base-20260924 streams; none overlap. Common-prefix, same/distinct pairing, profile, batch and dealer-role comparisons are retained. Exchanging proxy and Val did not establish a meaningful right-seat calling advantage.\n')
  for var in ['original','proxy-swapped']:
   for b in ['batch-1','batch-2']:lines.append(f"{var}/{b}: voluntary {estimate(s['seat'][f'strong/{var}/{b}/full']['voluntary_call_rate'])}; make rate {estimate(s['seat'][f'strong/{var}/{b}/full']['make_rate'])} percentage points.\n")
  lines.append('Observed result: a negative right-minus-left call-success estimate, with one exploratory pooled interval excluding zero. Statistical interpretation: an unadjusted follow-up signal among many comparisons. Suspected cause: unresolved; finite-seed variation and lineup/dealer interactions remain possible. Confirmed defect: none. No bot-versus-bot result measures the owner’s playing strength.\n')
lines.append('Cross-tier calibration\n')
lines.append('All 33 profile pairs ran 32 blocks each: two team assignments plus eight common-partner assignments. This is 2,112 team games and 8,448 common-partner games. Team estimates below are higher-tier win percentages (compare with 50%), and higher-tier final-score advantages. Common-partner estimates are higher-minus-lower changes, holding the other three policies at Balanced Strong and rotating the focal seat.\n')
for k in ['casual-vs-strong','strong-vs-expert','casual-vs-expert']:lines.append(k+'\n'+pairtext(k)+'\n')
teamreverse=[k for k,v in s['teams'].items() if '-balanced' in k or '-bold' in k or '-cautious' in k or '-conservative' in k or '-assertive' in k or '-partnership' in k if v['win']['estimate']<.5]
commonreverse=[k for k,v in s['common'].items() if k not in ['casual-vs-strong','strong-vs-expert','casual-vs-expert'] and v['win']['estimate']<0]
lines.append(f"No lower-tier team point estimate won a majority: observed team reversals {teamreverse}. No cross-tier three-profile cycle appears in these measured team edges; within-tier team edges were not all measured, so global transitivity is not established. Individual pair comparisons have only 32 blocks.\n")
for k in commonreverse:lines.append('Common-partner reversal: '+k+' '+estimate(s['common'][k]['win'])+' percentage points. This is an uncertain matchup, not a reason to tune labels.\n')
lines.append('Dealer positions, forced calls and loners\n')
forced=sum(v['forced_calls'] for v in s['profiles'].values());loners=sum(v['loner_attempts'] for v in s['profiles'].values());lines.append(f"All eleven policies contribute observations at dealer, first bidder, dealer’s partner and third bidder, split by round and forced status. There were {forced:,} forced second-round dealer calls and {loners:,} natural loner attempts. Each rate in the data carries numerator, denominator and denominator name. An opportunity is one bidding decision; a player can have opportunities in both rounds of a hand. Forced opportunities are excluded from voluntary rates. Undefined rates are null, not zero.\n")
lines.append('The readable dealer/loner appendix reports every profile, dealer role, round and forced-suit selection, including makes, euchres, gross earned points, conceded points and net points. controlled-hand-outcomes.json.gz supplies hand outcomes by controlled matchup and focal/opposing team. lineup-context.json.gz retains profile, seat, partner and both opponents. Descriptive pooled profile totals depend on the experiment mixture and are not strength rankings.\n')
for p,v in s['profiles'].items():lines.append(f"{p}: {v['loner_attempts']} natural attempts; {v['loner_five']} five-trick four-point successes; {v['loner_three_four']} three/four-trick one-point makes; {v['loner_euchres']} euchres.\n")
lines.append('Cautious Casual has only twelve natural attempts. Zero observed loner euchres for a policy is not zero risk; degenerate event-risk intervals are unavailable and sparse eligible blocks are flagged. Attempt rate alone cannot establish timidity or recklessness.\n')
lines.append(f"The separate scripted rule supplement ran {t['lonerHands']} loner hands across all dealer/caller positions, both rounds and four fixed seeds. Outcomes: {t['lonerOutcomes']}. All passed opening-lead, sit-out, skip order, pickup/discard and scoring checks. These deliberately forced calls are rule coverage, not natural strategy evidence.\n")
lines.append('Val-specific controlled and tactical evidence\n')
lines.append('Val and all four Strong alternatives each played 3,072 games: three partner tiers, all sixteen ordered Strong opponent pairs, four focal rotations, sixteen blocks/context. The 15,360 games contain 768 independent blocks. The same Val games serve multiple comparisons and are not new independent evidence each time.\n')
for p in ['strong-balanced','strong-conservative','strong-assertive','strong-partnership']:
 v=s['val'][p];lines.append(f"Val minus {p}: win {estimate(v['win'])} percentage points; score {estimate(v['score'],1)} points. Family-wise win interval: {estimate(v['win'],adjusted=True)}.\n")
lines.append('Balanced and Partnership pooled adjusted win intervals lie inside the plus/minus-five-point practical margin. This supports similarity only in these tested contexts. Conservative’s directional deficit does not establish a five-point minimum advantage for Val. Assertive’s apparent advantage does not survive the family-wise adjustment. Partner-specific and individual context estimates are exploratory; each context has only sixteen blocks.\n')
lines.append(f"The reconstructed tactical supplement ran {t['games']} complete games and retained {t['views']} permitted views, with context counts {t['contexts']}. A view can have multiple selected contexts. Its partner-return criterion explicitly means: the player has a lead choice and a completed trick was led by its partner and won by their team. This transparent reconstructed criterion yields a different targeted sample from the lost original supplement; no original tactical sample count is claimed as recovered.\n")
lines.append('All five policies receive exactly the same permitted view. Each chosen action is followed by fixed production-policy continuations on the actual host deal. Host state stays outside policy inputs. Action differences from Val: '+str(t['disagreements'])+'. The full views, actions and conditional hand outcomes are retained in fixtures.json.gz.\n')
for c in t['conditionalCosts'][:4]:lines.append(f"Conditional-cost example: seed {c['seed']}, hand {c['hand']}, decision {c['decision']}, seat {c['seat']}; Val {c['val']['action']} gives net {c['val']['outcome']['net']}, {c['alternative']['profile']} {c['alternative']['action']} gives net {c['alternative']['outcome']['net']}.\n")
lines.append('All five candidates overtook a winning partner in 3 of 64 selected positions, led trump in 22 of 64 lead choices, returned a previously partner-led team-won suit in 13 of 60 selected return opportunities, and played trump in 29 of 64 selected trump-conservation positions. These frequencies describe decisions; they are not mistake rates.\n')
lines.append('These are actual conditional differences, not an optimal-play oracle. One actual deal cannot establish which action is best across unseen deals compatible with the player’s information. Heuristic disagreement alone is not called a mistake. Leads, returns, conserving trump and overtaking partners are measured explicitly in tactical-summary.json.\n')
lines.append('Symmetry, validation and limitations\n')
for p,r in s['symmetry'].items():lines.append(p+': rotated all-same-policy right-minus-left voluntary rate '+estimate(r)+' percentage points.\n')
lines.append('The symmetry control uses four clockwise rotations with matched dealer rotation. No rule direction is reversed. Expert’s deterministic sampling depends on the permitted-view representation, so rotated action traces can differ; matching initial deals is verified independently.\n')
lines.append('Independent checks cover bidding order, four passes before turn-down, forbidden second-round suit, forced dealer calls, pickup/discard, ownership, effective follow-suit and bowers, every trick winner including the final trick, next leader, loner sit-out, card conservation, score increments, next dealer, termination, deterministic replay and the permitted-view boundary. Existing hidden-state noninterference tests remain in the baseline suite. No invariant failure was excluded from the schedule.\n')
lines.append('Audit-only defects corrected during development/recovery: the original tactical continuation cap of 25 was too short for a valid remaining bid/discard/play path; it is 29. The reconstructed return selector initially demanded that the immediately preceding trick was won by the current leader’s partner, which cannot be the current leader; it was replaced with the explicit historical team-won criterion above. Undefined/sparse-event bootstrap cases are handled without invented certainty. No engine or policy change followed these harness corrections.\n')
lines.append('Baseline npm ci --ignore-scripts, npm run check (131 tests), npm run build and git diff --check passed. The final validation logs record the rerun of those required commands and the completed suite. All 136 automated tests passed with zero failures. Seven statistical checks verify denominators, forced losses, loner distinctions, matched ratios, repeated observations, fixed-context weights and zero-event uncertainty. Expensive simulations remain on demand.\n')
lines.append('Limits: Expert seat effects and individual matchups remain imprecise. Policy-wide summaries mix the declared lineups. Loner attempts can be sparse. Runtime is specific to this Linux/Node environment, not iPhone latency. No optimal-play oracle, automatic learning, human-strength inference or VoiceOver acceptance is claimed.\n')
lines.append('Reproduction and files\n')
lines.append('Run python3 scripts/restore-bot-validation.py to materialize the compact committed results pack. Then node src/audit/validation-cli.ts --mode run --workers 4 validates and retains all completed chunks. The fixed manifest is reports/bot-validation/manifest.json. Recompute without replaying games: python3 scripts/analyze-bot-validation.py, then python3 scripts/report-bot-validation.py. Python 3 with NumPy and Node 24 are required. The ZIP includes all 336 individual detailed chunks directly, the report, manifest, fixtures, sources, validation logs and hashes.\n')
(D/'REPORT.md').write_text('\n'.join(lines))
# Plain-text comparison appendix, with explicit units and all exploratory strata.
text=['Controlled comparisons. Rates/wins are percentage points, score/net points retain point units. Subgroups are exploratory.\n']
for key,row in s['seat'].items():
 text.append('Seat '+key)
 for metric,x in row.items():text.append(metric+': '+estimate(x,1 if metric=='net_points_per_call' else 100))
for family in ['teams','common','val']:
 for key,row in s[family].items():
  text.append(family+' '+key)
  for metric,x in row.items():
   text.append(metric+': '+estimate(x,100 if metric=='win' else 1))
   if 'familyWise95' in x:text.append('family-wise: '+estimate(x,100 if metric=='win' else 1,True))
for key,x in s['profileContrasts'].items():text.append('Profile '+key+': '+estimate(x))
(O/'COMPARISONS.txt').write_text('\n'.join(text)+'\n')
text=['Dealer roles: 0 dealer; 1 first bidder; 2 dealer partner; 3 third bidder. Rates use exact listed denominators.\n']
for name in ['dealer-position','forced-suit']:
 text.append(name)
 for row in json.load(gzip.open(O/(name+'.json.gz'))):
  if 'suit_selection' in row:text.append('Suit selection count / all forced calls by this profile: '+str(row['suit_selection']['numerator'])+'/'+str(row['suit_selection']['denominator']))
  text.append(str(row['key'])+f": opportunities {row['opportunities']}; passes {row['passes']}; voluntary calls/opportunities {row['voluntary_calls']}/{row['voluntary_opportunities']}; forced calls {row['forced_calls']}; makes/calls {row['made']}/{row['calls']}; euchres/calls {row['euchred']}/{row['calls']}; gross {row['gross_points']}; conceded {row['gross_points']-row['net_points']}; net {row['net_points']}; maker tricks/calls {row['maker_tricks']}/{row['calls']}")
for p,row in s['profiles'].items():
 text.append(p+f": loners/calls {row['loner_attempts']}/{row['calls']}; five/attempts {row['loner_five']}/{row['loner_attempts']}; three-four/attempts {row['loner_three_four']}/{row['loner_attempts']}; euchres/attempts {row['loner_euchres']}/{row['loner_attempts']}")
(O/'DEALER_AND_LONERS.txt').write_text('\n'.join(text)+'\n')
print('Report and readable appendices regenerated.')
