import type { NarrationManifest } from './narration-types.ts';
// Generated by scripts/import-narrator-pack.ts from checksum/decode-verified assets.
export const narratorManifest: NarrationManifest = {
  "actor.you": {
    "id": "actor.you",
    "url": "audio/actor.you.mp3",
    "text": "You",
    "status": "ready",
    "durationSeconds": 0.417959,
    "sha256": "3dd205412a1bdd08b84110eeb268d056f5442a60d3dca0fe6aaec47e72d5122e",
    "bytes": 7148
  },
  "actor.val": {
    "id": "actor.val",
    "url": "audio/actor.val.mp3",
    "text": "Val",
    "status": "ready",
    "durationSeconds": 0.600816,
    "sha256": "1cb08e272443c7a833354f310410a185904c30f5647de75a2e65e78e3b5d30c7",
    "bytes": 10074
  },
  "actor.walt": {
    "id": "actor.walt",
    "url": "audio/actor.walt.mp3",
    "text": "Walt",
    "status": "ready",
    "durationSeconds": 0.653061,
    "sha256": "cc6aa38eb1fad91a3791698be71716791f136c2e764d949b2e834132bf1aa067",
    "bytes": 10910
  },
  "actor.emma": {
    "id": "actor.emma",
    "url": "audio/actor.emma.mp3",
    "text": "Emma",
    "status": "ready",
    "durationSeconds": 0.496327,
    "sha256": "770940d6ed8cf62262c1bca9c3795b8492dd391b68613f8570a20b26bbfe823a",
    "bytes": 8402
  },
  "actor.wes": {
    "id": "actor.wes",
    "url": "audio/actor.wes.mp3",
    "text": "Wes",
    "status": "ready",
    "durationSeconds": 0.783673,
    "sha256": "c242cab38e68808552ce27b7408c222b8727c82c7c0805133d00ee223302254e",
    "bytes": 12999
  },
  "actor.edith": {
    "id": "actor.edith",
    "url": "audio/actor.edith.mp3",
    "text": "Edith",
    "status": "ready",
    "durationSeconds": 0.470204,
    "sha256": "f2175aba3b253bc7792430950d983a92555fd1e282e77413da3afd34b5bb524d",
    "bytes": 7984
  },
  "actor.wyatt": {
    "id": "actor.wyatt",
    "url": "audio/actor.wyatt.mp3",
    "text": "Wyatt",
    "status": "ready",
    "durationSeconds": 0.600816,
    "sha256": "c17644707618e93c6f2d8535a359cdea09b2fea475895d6592f979a080992167",
    "bytes": 10074
  },
  "actor.eva": {
    "id": "actor.eva",
    "url": "audio/actor.eva.mp3",
    "text": "Eva",
    "status": "ready",
    "durationSeconds": 0.600816,
    "sha256": "18f6724f56dc2571ab3b4a41285da2e1aebda09733819bbe5b95c097a029ca75",
    "bytes": 10074
  },
  "actor.wayne": {
    "id": "actor.wayne",
    "url": "audio/actor.wayne.mp3",
    "text": "Wayne",
    "status": "ready",
    "durationSeconds": 0.653061,
    "sha256": "dd38abb7acf1ad42198e2c63499d6fed02ffaa54fa1876d10965ce7b9647a10d",
    "bytes": 10910
  },
  "actor.elise": {
    "id": "actor.elise",
    "url": "audio/actor.elise.mp3",
    "text": "Elise",
    "status": "ready",
    "durationSeconds": 0.653061,
    "sha256": "8dd58ea4a50c5988ad0f9e4815ccb4f4b12b35c7a3248aa3d760ae11840bc203",
    "bytes": 10910
  },
  "actor.will": {
    "id": "actor.will",
    "url": "audio/actor.will.mp3",
    "text": "Will",
    "status": "ready",
    "durationSeconds": 0.470204,
    "sha256": "1e3406eb39fd7772a5f643f469e8a9bd87f2460ee9160b6d911cc8278d61f5e0",
    "bytes": 7984
  },
  "actor.ellen": {
    "id": "actor.ellen",
    "url": "audio/actor.ellen.mp3",
    "text": "Ellen",
    "status": "ready",
    "durationSeconds": 0.470204,
    "sha256": "f4dbdb339189b0eb732040b3a7a363ae25e3b0338ead14d07be82661513b1f0b",
    "bytes": 7984
  },
  "actor.wade": {
    "id": "actor.wade",
    "url": "audio/actor.wade.mp3",
    "text": "Wade",
    "status": "ready",
    "durationSeconds": 0.653061,
    "sha256": "5eabc024713ca2ff7aa84f37f1e086f6c35262ee1b4dd17251529820db5e55bf",
    "bytes": 10910
  },
  "actor.erica": {
    "id": "actor.erica",
    "url": "audio/actor.erica.mp3",
    "text": "Erica",
    "status": "ready",
    "durationSeconds": 0.600816,
    "sha256": "f9ed60cdbcddba1e0822609e49f6c48c3510ea4cee20ab5332a52376f4547b47",
    "bytes": 10074
  },
  "actor.ward": {
    "id": "actor.ward",
    "url": "audio/actor.ward.mp3",
    "text": "Ward",
    "status": "ready",
    "durationSeconds": 0.705306,
    "sha256": "49163c11fc782b30adce0d729d71ce5e0cb26d784502bd05de0b64a3c924adfe",
    "bytes": 11745
  },
  "actor.erin": {
    "id": "actor.erin",
    "url": "audio/actor.erin.mp3",
    "text": "Erin",
    "status": "ready",
    "durationSeconds": 0.600816,
    "sha256": "b4a24acfd2728eae97af831e1fd933705ef8749c0fede520ebf5ef8619ad2a9b",
    "bytes": 10074
  },
  "actor.wolf": {
    "id": "actor.wolf",
    "url": "audio/actor.wolf.mp3",
    "text": "Wolf",
    "status": "ready",
    "durationSeconds": 0.783673,
    "sha256": "01c43854355aa6cc6e8b6e4485b2853e48233c6b3f7709bf56f0e45ee6867a1b",
    "bytes": 12999
  },
  "actor.elsa": {
    "id": "actor.elsa",
    "url": "audio/actor.elsa.mp3",
    "text": "Elsa",
    "status": "ready",
    "durationSeconds": 0.548571,
    "sha256": "4073020fd1bde0e7a5741f1f95f4bd03fb642b48d3c01665d74c584ac35d3d4e",
    "bytes": 9238
  },
  "actor.wren": {
    "id": "actor.wren",
    "url": "audio/actor.wren.mp3",
    "text": "Wren",
    "status": "ready",
    "durationSeconds": 0.548571,
    "sha256": "b36430daf33736342c3b7e3855b285d11968a5ad5d7394dffd2f668b3574c6e7",
    "bytes": 9238
  },
  "actor.etta": {
    "id": "actor.etta",
    "url": "audio/actor.etta.mp3",
    "text": "Etta",
    "status": "ready",
    "durationSeconds": 0.417959,
    "sha256": "2e25281ab35db474fb3983ca0ae2680a2d166a2ec219b83a230ed29a555f46eb",
    "bytes": 7148
  },
  "actor.webb": {
    "id": "actor.webb",
    "url": "audio/actor.webb.mp3",
    "text": "Webb",
    "status": "ready",
    "durationSeconds": 0.705306,
    "sha256": "6780a51a0a6895920a447914417416df62a88a7e522cfa4b6c134ab179e44021",
    "bytes": 11745
  },
  "actor.eden": {
    "id": "actor.eden",
    "url": "audio/actor.eden.mp3",
    "text": "Eden",
    "status": "ready",
    "durationSeconds": 0.548571,
    "sha256": "dbc162d023da8fe06a71c4bdeddcf46b148e136aaac6ab70695a12547bfad7e1",
    "bytes": 9238
  },
  "actor.west": {
    "id": "actor.west",
    "url": "audio/actor.west.mp3",
    "text": "West",
    "status": "ready",
    "durationSeconds": 0.600816,
    "sha256": "3c37aed38503a1606c655012ed6f7f3646a12ef43ebf90377b38de443fd648cf",
    "bytes": 10074
  },
  "actor.east": {
    "id": "actor.east",
    "url": "audio/actor.east.mp3",
    "text": "East",
    "status": "ready",
    "durationSeconds": 0.496327,
    "sha256": "35887236d5bf75c2a16089013784c217ca812ebc03124ccbd356d6d1f315393b",
    "bytes": 8402
  },
  "prefix.val.plays": {
    "id": "prefix.val.plays",
    "url": "audio/prefix.val.plays.mp3",
    "text": "Val plays",
    "status": "ready",
    "durationSeconds": 1.123265,
    "sha256": "1f3baab33148ff15959994c58f0a087a7ec3c4aca5764e2daad6b15d35c1acfd",
    "bytes": 18433
  },
  "prefix.val.leads": {
    "id": "prefix.val.leads",
    "url": "audio/prefix.val.leads.mp3",
    "text": "Val leads",
    "status": "ready",
    "durationSeconds": 1.123265,
    "sha256": "7eca7c714f9bc8d48b80c8d3f401db304bd971da95fa94c7f5965ae57ed5df7a",
    "bytes": 18433
  },
  "prefix.walt.plays": {
    "id": "prefix.walt.plays",
    "url": "audio/prefix.walt.plays.mp3",
    "text": "Walt plays",
    "status": "ready",
    "durationSeconds": 1.201633,
    "sha256": "7c23c4b1db3a2723da4037f801f64caed5c99c2cfe7d0685696c99908439806e",
    "bytes": 19687
  },
  "prefix.walt.leads": {
    "id": "prefix.walt.leads",
    "url": "audio/prefix.walt.leads.mp3",
    "text": "Walt leads",
    "status": "ready",
    "durationSeconds": 1.306122,
    "sha256": "3b3a2d96e1bfdc2cd7c5668ba14ddfdd0f98b3bf938ff715e88e87a32af23647",
    "bytes": 21358
  },
  "prefix.emma.plays": {
    "id": "prefix.emma.plays",
    "url": "audio/prefix.emma.plays.mp3",
    "text": "Emma plays",
    "status": "ready",
    "durationSeconds": 1.07102,
    "sha256": "6dae3aa1f170c5fc4da38d9badbe73009fc6c0a1f7121872a0c2fa4083de5ab3",
    "bytes": 17597
  },
  "prefix.emma.leads": {
    "id": "prefix.emma.leads",
    "url": "audio/prefix.emma.leads.mp3",
    "text": "Emma leads",
    "status": "ready",
    "durationSeconds": 0.783673,
    "sha256": "862a49eaa3b2bf52a4862b49d4c5fa680d2e29aaf651f83ca33c997d87fe1083",
    "bytes": 12999
  },
  "prefix.wes.plays": {
    "id": "prefix.wes.plays",
    "url": "audio/prefix.wes.plays.mp3",
    "text": "Wes plays",
    "status": "ready",
    "durationSeconds": 1.253878,
    "sha256": "c6ecff49a2ca32962e9d82a786502473d94c07a0b89c5f1eefec685d8f370672",
    "bytes": 20523
  },
  "prefix.wes.leads": {
    "id": "prefix.wes.leads",
    "url": "audio/prefix.wes.leads.mp3",
    "text": "Wes leads",
    "status": "ready",
    "durationSeconds": 1.123265,
    "sha256": "96e145dbb03d27a013c841b2c24de50d2d06f98e9c8a70a2b3e6f32fbd374eda",
    "bytes": 18433
  },
  "prefix.edith.plays": {
    "id": "prefix.edith.plays",
    "url": "audio/prefix.edith.plays.mp3",
    "text": "Edith plays",
    "status": "ready",
    "durationSeconds": 1.201633,
    "sha256": "6fbbb9de9c84967fec588a61fececcd13f591b6768008f6be478d3336eec5a0a",
    "bytes": 19687
  },
  "prefix.edith.leads": {
    "id": "prefix.edith.leads",
    "url": "audio/prefix.edith.leads.mp3",
    "text": "Edith leads",
    "status": "ready",
    "durationSeconds": 1.018776,
    "sha256": "8eef6fbf73824a3870c9581af10f540bf7de000bd5db3899de7e57b8df100a9b",
    "bytes": 16761
  },
  "prefix.wyatt.plays": {
    "id": "prefix.wyatt.plays",
    "url": "audio/prefix.wyatt.plays.mp3",
    "text": "Wyatt plays",
    "status": "ready",
    "durationSeconds": 1.07102,
    "sha256": "88f7094c6a2f6d41bd2336f035c993d820c5fcd82ef8926beb8fbdd15c04f74d",
    "bytes": 17597
  },
  "prefix.wyatt.leads": {
    "id": "prefix.wyatt.leads",
    "url": "audio/prefix.wyatt.leads.mp3",
    "text": "Wyatt leads",
    "status": "ready",
    "durationSeconds": 1.149388,
    "sha256": "2c1230b6bcad78d0385a9d524fc733b6ea18fb62bfb3bd4b51ce2a8d5baa07c3",
    "bytes": 18851
  },
  "prefix.eva.plays": {
    "id": "prefix.eva.plays",
    "url": "audio/prefix.eva.plays.mp3",
    "text": "Eva plays",
    "status": "ready",
    "durationSeconds": 1.123265,
    "sha256": "eec02b5d0444beed2a6f75a6c6f1c6ce8ccc70f3dbac4603975172469412ec31",
    "bytes": 18433
  },
  "prefix.eva.leads": {
    "id": "prefix.eva.leads",
    "url": "audio/prefix.eva.leads.mp3",
    "text": "Eva leads",
    "status": "ready",
    "durationSeconds": 0.783673,
    "sha256": "e7bdc30a2226c8803c5f8d83c36f80980a8f30293cc0d421cb868d9942e9de79",
    "bytes": 12999
  },
  "prefix.wayne.plays": {
    "id": "prefix.wayne.plays",
    "url": "audio/prefix.wayne.plays.mp3",
    "text": "Wayne plays",
    "status": "ready",
    "durationSeconds": 1.306122,
    "sha256": "3a070b480316745684681d984e7db2d0ab1cf17ba9c0feacae7b82d41546ffbf",
    "bytes": 21358
  },
  "prefix.wayne.leads": {
    "id": "prefix.wayne.leads",
    "url": "audio/prefix.wayne.leads.mp3",
    "text": "Wayne leads",
    "status": "ready",
    "durationSeconds": 1.07102,
    "sha256": "4b4d21fb5862e03cdc8d9c6008b710968d49e1238712f71eb2645847240d5b9d",
    "bytes": 17597
  },
  "prefix.elise.plays": {
    "id": "prefix.elise.plays",
    "url": "audio/prefix.elise.plays.mp3",
    "text": "Elise plays",
    "status": "ready",
    "durationSeconds": 0.966531,
    "sha256": "c7231bb2549d86c9ce99ced8282ae974285141b0a97b8e220b42d0bf92cef9b4",
    "bytes": 15925
  },
  "prefix.elise.leads": {
    "id": "prefix.elise.leads",
    "url": "audio/prefix.elise.leads.mp3",
    "text": "Elise leads",
    "status": "ready",
    "durationSeconds": 1.201633,
    "sha256": "aaba96efe77d671ce92b0b84ef70994d844884b20df1f1f484882ae618272b80",
    "bytes": 19687
  },
  "prefix.will.plays": {
    "id": "prefix.will.plays",
    "url": "audio/prefix.will.plays.mp3",
    "text": "Will plays",
    "status": "ready",
    "durationSeconds": 1.149388,
    "sha256": "46855e289c4ed9307cfdedf0e7cf19ccb234bf6b7da6305188f63a3825d3016a",
    "bytes": 18851
  },
  "prefix.will.leads": {
    "id": "prefix.will.leads",
    "url": "audio/prefix.will.leads.mp3",
    "text": "Will leads",
    "status": "ready",
    "durationSeconds": 1.018776,
    "sha256": "9ccc814a6020e13608df5ab5fd8f36404aaf9b5891dba79904171e906e6ccb6a",
    "bytes": 16761
  },
  "prefix.ellen.plays": {
    "id": "prefix.ellen.plays",
    "url": "audio/prefix.ellen.plays.mp3",
    "text": "Ellen plays",
    "status": "ready",
    "durationSeconds": 1.123265,
    "sha256": "c7485b36c85c6909792c48f86143e416352f24efbfdef9d8e5d5eba70892d4e8",
    "bytes": 18433
  },
  "prefix.ellen.leads": {
    "id": "prefix.ellen.leads",
    "url": "audio/prefix.ellen.leads.mp3",
    "text": "Ellen leads",
    "status": "ready",
    "durationSeconds": 0.888163,
    "sha256": "43d0f7b8163170872809665f0c01330f1543bc3a32404c86a7a962a1672aa8df",
    "bytes": 14671
  },
  "prefix.wade.plays": {
    "id": "prefix.wade.plays",
    "url": "audio/prefix.wade.plays.mp3",
    "text": "Wade plays",
    "status": "ready",
    "durationSeconds": 1.123265,
    "sha256": "68774064e34e2cef88bcc108310fa38b2daa0b33fad0de5eb3377747288a0d8d",
    "bytes": 18433
  },
  "prefix.wade.leads": {
    "id": "prefix.wade.leads",
    "url": "audio/prefix.wade.leads.mp3",
    "text": "Wade leads",
    "status": "ready",
    "durationSeconds": 1.018776,
    "sha256": "0ff90b29fa8f7ba54e28ca9735a9f8650afb3e7f8cd7655b477e7fde6f591be7",
    "bytes": 16761
  },
  "prefix.erica.plays": {
    "id": "prefix.erica.plays",
    "url": "audio/prefix.erica.plays.mp3",
    "text": "Erica plays",
    "status": "ready",
    "durationSeconds": 1.07102,
    "sha256": "98dd0b12d7fce0f4fbb27698c1751a4ae3eef5a1ed4be6919536289162653b64",
    "bytes": 17597
  },
  "prefix.erica.leads": {
    "id": "prefix.erica.leads",
    "url": "audio/prefix.erica.leads.mp3",
    "text": "Erica leads",
    "status": "ready",
    "durationSeconds": 1.149388,
    "sha256": "6538c56f5b877ed4d9a20b3901eb0aec21a42af3e2c568bf5956e61b42f70a13",
    "bytes": 18851
  },
  "prefix.ward.plays": {
    "id": "prefix.ward.plays",
    "url": "audio/prefix.ward.plays.mp3",
    "text": "Ward plays",
    "status": "ready",
    "durationSeconds": 1.123265,
    "sha256": "ce3c9c2b77c98bffa49bf1b2dd81ab7ca80a3ff1fece3a6a53a11a6bc7f1f3c2",
    "bytes": 18433
  },
  "prefix.ward.leads": {
    "id": "prefix.ward.leads",
    "url": "audio/prefix.ward.leads.mp3",
    "text": "Ward leads",
    "status": "ready",
    "durationSeconds": 1.123265,
    "sha256": "f1b4850a4f235c41df426d4fce8fe1ec14bd298a052247095e3b0cca693fee9d",
    "bytes": 18433
  },
  "prefix.erin.plays": {
    "id": "prefix.erin.plays",
    "url": "audio/prefix.erin.plays.mp3",
    "text": "Erin plays",
    "status": "ready",
    "durationSeconds": 1.07102,
    "sha256": "11c3530dea47d08fef5890e52d2c8a4484edfccc2a3a461565ff4e267c0dc4e1",
    "bytes": 17597
  },
  "prefix.erin.leads": {
    "id": "prefix.erin.leads",
    "url": "audio/prefix.erin.leads.mp3",
    "text": "Erin leads",
    "status": "ready",
    "durationSeconds": 1.07102,
    "sha256": "c33fd3a766d3484d4c2fb558d12efc30f1815fe2838ea13dd40e05634a6a9205",
    "bytes": 17597
  },
  "prefix.wolf.plays": {
    "id": "prefix.wolf.plays",
    "url": "audio/prefix.wolf.plays.mp3",
    "text": "Wolf plays",
    "status": "ready",
    "durationSeconds": 1.201633,
    "sha256": "69b75da31674d94b6b9e58676ddcd096d9dcd7be70f37e640228a71717607046",
    "bytes": 19687
  },
  "prefix.wolf.leads": {
    "id": "prefix.wolf.leads",
    "url": "audio/prefix.wolf.leads.mp3",
    "text": "Wolf leads",
    "status": "ready",
    "durationSeconds": 1.07102,
    "sha256": "c33ca783c304a95bf1aaba9c4849b74d7f888b5763b85144b5b26b7678515bb5",
    "bytes": 17597
  },
  "prefix.elsa.plays": {
    "id": "prefix.elsa.plays",
    "url": "audio/prefix.elsa.plays.mp3",
    "text": "Elsa plays",
    "status": "ready",
    "durationSeconds": 1.201633,
    "sha256": "679000e04e10dae77e7f5b134ec5e77a8e8852c5f1b878017544429754539a96",
    "bytes": 19687
  },
  "prefix.elsa.leads": {
    "id": "prefix.elsa.leads",
    "url": "audio/prefix.elsa.leads.mp3",
    "text": "Elsa leads",
    "status": "ready",
    "durationSeconds": 0.966531,
    "sha256": "a8ae1f27197edff74f41a63d16f7cb4c756a4ef24ba2934fb53e9aab6654889d",
    "bytes": 15925
  },
  "prefix.wren.plays": {
    "id": "prefix.wren.plays",
    "url": "audio/prefix.wren.plays.mp3",
    "text": "Wren plays",
    "status": "ready",
    "durationSeconds": 1.306122,
    "sha256": "f1aae9ac42141cf8ddbb62c73a0ad8f8cdab2c9c52e69de0a943a440d66a482b",
    "bytes": 21358
  },
  "prefix.wren.leads": {
    "id": "prefix.wren.leads",
    "url": "audio/prefix.wren.leads.mp3",
    "text": "Wren leads",
    "status": "ready",
    "durationSeconds": 0.966531,
    "sha256": "e8fb53ebf672bad7f9bcc85d022ad44ea4ed74fc801e1bf0a37bb746728075d4",
    "bytes": 15925
  },
  "prefix.etta.plays": {
    "id": "prefix.etta.plays",
    "url": "audio/prefix.etta.plays.mp3",
    "text": "Etta plays",
    "status": "ready",
    "durationSeconds": 1.306122,
    "sha256": "a1622cf3555b88ac3dfeafded610da37da7fb02a11df7da9d1a688fdf866bbe9",
    "bytes": 21358
  },
  "prefix.etta.leads": {
    "id": "prefix.etta.leads",
    "url": "audio/prefix.etta.leads.mp3",
    "text": "Etta leads",
    "status": "ready",
    "durationSeconds": 0.966531,
    "sha256": "b524c2718dfcfab2a0b0684032ca830898bfab8cb9512e5a753edb32f3730340",
    "bytes": 15925
  },
  "prefix.webb.plays": {
    "id": "prefix.webb.plays",
    "url": "audio/prefix.webb.plays.mp3",
    "text": "Webb plays",
    "status": "ready",
    "durationSeconds": 1.07102,
    "sha256": "4b55d248c75279a15f9323813395ed790bcd6721e7d56760722a066fdac2861e",
    "bytes": 17597
  },
  "prefix.webb.leads": {
    "id": "prefix.webb.leads",
    "url": "audio/prefix.webb.leads.mp3",
    "text": "Webb leads",
    "status": "ready",
    "durationSeconds": 0.888163,
    "sha256": "740947efcb322a8a3c636f8c69ff9e70ed030df725f1804f4cc770094b28f9d4",
    "bytes": 14671
  },
  "prefix.eden.plays": {
    "id": "prefix.eden.plays",
    "url": "audio/prefix.eden.plays.mp3",
    "text": "Eden plays",
    "status": "ready",
    "durationSeconds": 1.201633,
    "sha256": "a5371766a6c8792dfe17ee25dd28bd8f20b961a72540288a86f447baf3a18c58",
    "bytes": 19687
  },
  "prefix.eden.leads": {
    "id": "prefix.eden.leads",
    "url": "audio/prefix.eden.leads.mp3",
    "text": "Eden leads",
    "status": "ready",
    "durationSeconds": 1.149388,
    "sha256": "859ce98c3db6b46d3120633449ed2c6c72372b24e6c36a42bef90ab44326fe1e",
    "bytes": 18851
  },
  "prefix.west.plays": {
    "id": "prefix.west.plays",
    "url": "audio/prefix.west.plays.mp3",
    "text": "West plays",
    "status": "ready",
    "durationSeconds": 1.253878,
    "sha256": "7a5f22f56120962a6fce6c4f8b8f5fcd2c76c1b064128f30b9935695bc44adf5",
    "bytes": 20523
  },
  "prefix.west.leads": {
    "id": "prefix.west.leads",
    "url": "audio/prefix.west.leads.mp3",
    "text": "West leads",
    "status": "ready",
    "durationSeconds": 1.018776,
    "sha256": "acf0165167ea26a9a6421d405ae8f4dde339e9e5aae66315e7c85014a8d53e86",
    "bytes": 16761
  },
  "prefix.east.plays": {
    "id": "prefix.east.plays",
    "url": "audio/prefix.east.plays.mp3",
    "text": "East plays",
    "status": "ready",
    "durationSeconds": 1.253878,
    "sha256": "715d6f28e0a52e3d47052ee3ba26eceed7aa5de5cc65205bf70b30bfdac9e551",
    "bytes": 20523
  },
  "prefix.east.leads": {
    "id": "prefix.east.leads",
    "url": "audio/prefix.east.leads.mp3",
    "text": "East leads",
    "status": "ready",
    "durationSeconds": 1.253878,
    "sha256": "906355442083b300e457435f8516cddd5c17e3a1345819314bb648666e1bae47",
    "bytes": 20523
  },
  "card.clubs.9": {
    "id": "card.clubs.9",
    "url": "audio/card.clubs.9.mp3",
    "text": "nine of clubs.",
    "status": "ready",
    "durationSeconds": 1.253878,
    "sha256": "5578adc14130dcccba7fc3566cd8e3c59b6528e1859d0a525356c8e5034c5611",
    "bytes": 20523
  },
  "card.clubs.10": {
    "id": "card.clubs.10",
    "url": "audio/card.clubs.10.mp3",
    "text": "ten of clubs.",
    "status": "ready",
    "durationSeconds": 1.018776,
    "sha256": "e1ee80cefc2d57ae10c56501c29983ba3fe62bdf4483bee4a25e849933e50e0e",
    "bytes": 16761
  },
  "card.clubs.j": {
    "id": "card.clubs.j",
    "url": "audio/card.clubs.j.mp3",
    "text": "jack of clubs.",
    "status": "ready",
    "durationSeconds": 1.201633,
    "sha256": "db24d9527c6e41c936ad4bcdedda69f13c9ab93dce1a7bed4ca2e25a56c3c77d",
    "bytes": 19687
  },
  "card.clubs.q": {
    "id": "card.clubs.q",
    "url": "audio/card.clubs.q.mp3",
    "text": "queen of clubs.",
    "status": "ready",
    "durationSeconds": 1.018776,
    "sha256": "58d187dcfef1d144172e9b24c073536d36bfd66b805c2140e2c04681f31d5169",
    "bytes": 16761
  },
  "card.clubs.k": {
    "id": "card.clubs.k",
    "url": "audio/card.clubs.k.mp3",
    "text": "king of clubs.",
    "status": "ready",
    "durationSeconds": 1.123265,
    "sha256": "f9ddc556f227447f922351e736e45db0d878bd3eed463693dd90d6a76d9bbd28",
    "bytes": 18433
  },
  "card.clubs.a": {
    "id": "card.clubs.a",
    "url": "audio/card.clubs.a.mp3",
    "text": "ace of clubs.",
    "status": "ready",
    "durationSeconds": 1.07102,
    "sha256": "72ab04e877a48e93386c89aa3c6cf205496f6eca407655cd8b255976d21e1ab5",
    "bytes": 17597
  },
  "card.diamonds.9": {
    "id": "card.diamonds.9",
    "url": "audio/card.diamonds.9.mp3",
    "text": "nine of diamonds.",
    "status": "ready",
    "durationSeconds": 1.253878,
    "sha256": "c0a77cf84630cbc7c467c77af1df9905ca203a48cac23d59bc1ffec4ae5ee9ab",
    "bytes": 20523
  },
  "card.diamonds.10": {
    "id": "card.diamonds.10",
    "url": "audio/card.diamonds.10.mp3",
    "text": "ten of diamonds.",
    "status": "ready",
    "durationSeconds": 1.332245,
    "sha256": "e2263814a994dac8ea5cba99b20ff095774d532140372b9ca4fcc27ce106a2ef",
    "bytes": 21776
  },
  "card.diamonds.j": {
    "id": "card.diamonds.j",
    "url": "audio/card.diamonds.j.mp3",
    "text": "jack of diamonds.",
    "status": "ready",
    "durationSeconds": 1.332245,
    "sha256": "fb7aaf16f2f4789a02502a4dbb48ce8e74e03ddc290d6f3476468a4b784102f2",
    "bytes": 21776
  },
  "card.diamonds.q": {
    "id": "card.diamonds.q",
    "url": "audio/card.diamonds.q.mp3",
    "text": "queen of diamonds.",
    "status": "ready",
    "durationSeconds": 1.253878,
    "sha256": "9a5d2d7c6d2329a170849a83ecf8f85a421a6ee71f769647456ecd4a8ead383e",
    "bytes": 20523
  },
  "card.diamonds.k": {
    "id": "card.diamonds.k",
    "url": "audio/card.diamonds.k.mp3",
    "text": "king of diamonds.",
    "status": "ready",
    "durationSeconds": 1.253878,
    "sha256": "629e931db599282fccb4a517accf55538be303b1c3ce7bb5dad75ea387ab35ad",
    "bytes": 20523
  },
  "card.diamonds.a": {
    "id": "card.diamonds.a",
    "url": "audio/card.diamonds.a.mp3",
    "text": "ace of diamonds.",
    "status": "ready",
    "durationSeconds": 1.253878,
    "sha256": "7ecb0057d60d9aff55a34f5d27fd412a72488af69218693b1f10493193b591f4",
    "bytes": 20523
  },
  "card.hearts.9": {
    "id": "card.hearts.9",
    "url": "audio/card.hearts.9.mp3",
    "text": "nine of hearts.",
    "status": "ready",
    "durationSeconds": 1.306122,
    "sha256": "f14c207def95585562a1f27db48f2626073e3fdc2db0becb838e29aab4923f68",
    "bytes": 21358
  },
  "card.hearts.10": {
    "id": "card.hearts.10",
    "url": "audio/card.hearts.10.mp3",
    "text": "ten of hearts.",
    "status": "ready",
    "durationSeconds": 0.888163,
    "sha256": "00df0006559b10e44d4396eebd50eac4db9c5bedfbcba2bd8281dad972d752e8",
    "bytes": 14671
  },
  "card.hearts.j": {
    "id": "card.hearts.j",
    "url": "audio/card.hearts.j.mp3",
    "text": "jack of hearts.",
    "status": "ready",
    "durationSeconds": 1.149388,
    "sha256": "5169bacedf7cc21853d8e7408d97a596c0ef513b618a4679e97c2e2f5a02ef0a",
    "bytes": 18851
  },
  "card.hearts.q": {
    "id": "card.hearts.q",
    "url": "audio/card.hearts.q.mp3",
    "text": "queen of hearts.",
    "status": "ready",
    "durationSeconds": 1.123265,
    "sha256": "a6a6edfcb49855650e8f3389d0c47cc9de5ee7924278f99591cfc8af0ee2e6fb",
    "bytes": 18433
  },
  "card.hearts.k": {
    "id": "card.hearts.k",
    "url": "audio/card.hearts.k.mp3",
    "text": "king of hearts.",
    "status": "ready",
    "durationSeconds": 1.201633,
    "sha256": "85f92b2dc474c6e6f719cea96681a8d7a8cef8a195bc625342e57fb022e81f30",
    "bytes": 19687
  },
  "card.hearts.a": {
    "id": "card.hearts.a",
    "url": "audio/card.hearts.a.mp3",
    "text": "ace of hearts.",
    "status": "ready",
    "durationSeconds": 1.07102,
    "sha256": "8fd730ce2dc9383c3c5e75da8798518382611ea99a75a33fdb2fcf0c3d580d97",
    "bytes": 17597
  },
  "card.spades.9": {
    "id": "card.spades.9",
    "url": "audio/card.spades.9.mp3",
    "text": "nine of spades.",
    "status": "ready",
    "durationSeconds": 1.436735,
    "sha256": "02997dae45a1f69f4cec239b3cec0a048707790a3e88ac9067af8c098e09e785",
    "bytes": 23448
  },
  "card.spades.10": {
    "id": "card.spades.10",
    "url": "audio/card.spades.10.mp3",
    "text": "ten of spades.",
    "status": "ready",
    "durationSeconds": 1.436735,
    "sha256": "066c61e301ef8966f1353a8b3c965ad1fea5a2f3639cfc06d6d30f39ed9faa98",
    "bytes": 23448
  },
  "card.spades.j": {
    "id": "card.spades.j",
    "url": "audio/card.spades.j.mp3",
    "text": "jack of spades.",
    "status": "ready",
    "durationSeconds": 1.436735,
    "sha256": "befb4141455760ab26f5ca6bccd443e26009c8c04a623a204b2ddbad7426c560",
    "bytes": 23448
  },
  "card.spades.q": {
    "id": "card.spades.q",
    "url": "audio/card.spades.q.mp3",
    "text": "queen of spades.",
    "status": "ready",
    "durationSeconds": 1.201633,
    "sha256": "ff1a451b2dc441e5556e9d34245388266002e66167f70c572f8e5b16915997ef",
    "bytes": 19687
  },
  "card.spades.k": {
    "id": "card.spades.k",
    "url": "audio/card.spades.k.mp3",
    "text": "king of spades.",
    "status": "ready",
    "durationSeconds": 1.436735,
    "sha256": "f11987c5240df2b2f7ef1b4e87597ec89dedc3801c503901dc33f6b9578c8225",
    "bytes": 23448
  },
  "card.spades.a": {
    "id": "card.spades.a",
    "url": "audio/card.spades.a.mp3",
    "text": "ace of spades.",
    "status": "ready",
    "durationSeconds": 1.253878,
    "sha256": "2d6f8e1ff22d5ea34df33838089e0f3b4a147b5db814aa19cbd3372c4cfb5060",
    "bytes": 20523
  },
  "bower.right.clubs": {
    "id": "bower.right.clubs",
    "url": "audio/bower.right.clubs.mp3",
    "text": "jack of clubs, right bower.",
    "status": "ready",
    "durationSeconds": 2.037551,
    "sha256": "6f9d575523074364263984ac4c9c814e09113ec99fba82debb95d660f05a2053",
    "bytes": 33061
  },
  "bower.left.clubs": {
    "id": "bower.left.clubs",
    "url": "audio/bower.left.clubs.mp3",
    "text": "jack of clubs, left bower, counts as spades.",
    "status": "ready",
    "durationSeconds": 3.474286,
    "sha256": "57e9dd1c128aee6a6c61452994a7f56792f19e1956af18d2d9c69d8391c20002",
    "bytes": 56049
  },
  "bower.right.diamonds": {
    "id": "bower.right.diamonds",
    "url": "audio/bower.right.diamonds.mp3",
    "text": "jack of diamonds, right bower.",
    "status": "ready",
    "durationSeconds": 1.906939,
    "sha256": "70a9fcee6654c0829d58aebbdd56987e1b9dfbcd4d6f4fbede186fde929de6b4",
    "bytes": 30972
  },
  "bower.left.diamonds": {
    "id": "bower.left.diamonds",
    "url": "audio/bower.left.diamonds.mp3",
    "text": "jack of diamonds, left bower, counts as hearts.",
    "status": "ready",
    "durationSeconds": 3.056327,
    "sha256": "2353887d72134537d71a01b0575c843320eb9c7f4846912a3ddc01651050d8a5",
    "bytes": 49362
  },
  "bower.right.hearts": {
    "id": "bower.right.hearts",
    "url": "audio/bower.right.hearts.mp3",
    "text": "jack of hearts, right bower.",
    "status": "ready",
    "durationSeconds": 2.220408,
    "sha256": "7c89a564258be7c72c669c52833cb13e98cb811fa7acf681f348f4bd123a017c",
    "bytes": 35987
  },
  "bower.left.hearts": {
    "id": "bower.left.hearts",
    "url": "audio/bower.left.hearts.mp3",
    "text": "jack of hearts, left bower, counts as diamonds.",
    "status": "ready",
    "durationSeconds": 3.160816,
    "sha256": "c5c610329afdb23a09d493121ff25203e980e9bd7e19541c65278e26df59bf5d",
    "bytes": 51034
  },
  "bower.right.spades": {
    "id": "bower.right.spades",
    "url": "audio/bower.right.spades.mp3",
    "text": "jack of spades, right bower.",
    "status": "ready",
    "durationSeconds": 1.985306,
    "sha256": "aecb99eb8afc8913025f7ab9830d6c74ed2ce67d4ed6a60b30543801d676f535",
    "bytes": 32225
  },
  "bower.left.spades": {
    "id": "bower.left.spades",
    "url": "audio/bower.left.spades.mp3",
    "text": "jack of spades, left bower, counts as clubs.",
    "status": "ready",
    "durationSeconds": 3.160816,
    "sha256": "a93dbaf01b2adff3b50556f3d7271cb4b50ee5007d0423d63c962ea136842b75",
    "bytes": 51034
  },
  "event.plays": {
    "id": "event.plays",
    "url": "audio/event.plays.mp3",
    "text": "plays",
    "status": "ready",
    "durationSeconds": 0.705306,
    "sha256": "6fe5994e42128271b5ca3067a6adda6ffc4dccb3bfb4a9e9aa1e137b4e2ff1af",
    "bytes": 11745
  },
  "event.leads": {
    "id": "event.leads",
    "url": "audio/event.leads.mp3",
    "text": "leads",
    "status": "ready",
    "durationSeconds": 0.653061,
    "sha256": "0b060b44293103c81c025c457823dfa9d52a5d7fed909a02e65e2cb69ae57a7a",
    "bytes": 10910
  },
  "event.passes": {
    "id": "event.passes",
    "url": "audio/event.passes.mp3",
    "text": "passes.",
    "status": "ready",
    "durationSeconds": 0.600816,
    "sha256": "e9ac59f0191fe93cb183f897a510eb902999656a12eceaabbe8ab2f51f4cdaa0",
    "bytes": 10074
  },
  "event.deals": {
    "id": "event.deals",
    "url": "audio/event.deals.mp3",
    "text": "deals.",
    "status": "ready",
    "durationSeconds": 0.731429,
    "sha256": "4d6f1253222b1719f39d7c10d3b21dc263d5329bdeca7d250c0cf126f78d998d",
    "bytes": 12163
  },
  "event.deal": {
    "id": "event.deal",
    "url": "audio/event.deal.mp3",
    "text": "deal.",
    "status": "ready",
    "durationSeconds": 0.496327,
    "sha256": "6546ce37aa48e2042eaeebafdb0dd72f6c60b22eafff42885b6faab04ffb56a2",
    "bytes": 8402
  },
  "event.picks-up": {
    "id": "event.picks-up",
    "url": "audio/event.picks-up.mp3",
    "text": "picks up.",
    "status": "ready",
    "durationSeconds": 0.600816,
    "sha256": "0314bb9fc08f43f6f1eb4d6e6336ae236ddf93cd4c4c242a37fd766884e26a0d",
    "bytes": 10074
  },
  "event.pick-up": {
    "id": "event.pick-up",
    "url": "audio/event.pick-up.mp3",
    "text": "pick up.",
    "status": "ready",
    "durationSeconds": 0.600816,
    "sha256": "9b59bb948909f6dc586e99865e032cae731765efed9e2930a42655d43ee70548",
    "bytes": 10074
  },
  "event.discards": {
    "id": "event.discards",
    "url": "audio/event.discards.mp3",
    "text": "discards a card.",
    "status": "ready",
    "durationSeconds": 1.48898,
    "sha256": "fa59c519801f1666febc4c56414a12586e77c6561ddc9feb4843a27135c15591",
    "bytes": 24284
  },
  "event.takes-trick": {
    "id": "event.takes-trick",
    "url": "audio/event.takes-trick.mp3",
    "text": "takes the trick.",
    "status": "ready",
    "durationSeconds": 0.888163,
    "sha256": "7053fc9c9e439f22bdd154834494f1df16f170f9cd4941c8324a8b99777bb004",
    "bytes": 14671
  },
  "event.take-trick": {
    "id": "event.take-trick",
    "url": "audio/event.take-trick.mp3",
    "text": "take the trick.",
    "status": "ready",
    "durationSeconds": 0.888163,
    "sha256": "83ee5b7628408f1fc568632f0e52f291d106aa7da638ccdd8677bf4fd40b7cc4",
    "bytes": 14671
  },
  "event.goes-alone": {
    "id": "event.goes-alone",
    "url": "audio/event.goes-alone.mp3",
    "text": "and goes alone.",
    "status": "ready",
    "durationSeconds": 0.966531,
    "sha256": "4d929e1190aa2e51d4c6fc03f186f1e8852eff8078864ecea6e3b017d0aa8e5a",
    "bytes": 15925
  },
  "event.up-card": {
    "id": "event.up-card",
    "url": "audio/event.up-card.mp3",
    "text": "Up-card:",
    "status": "ready",
    "durationSeconds": 0.653061,
    "sha256": "86862bb52f1915d2ab4ce48312e797a73fb88f2fc89373c2bff23ded080ed3cf",
    "bytes": 10910
  },
  "event.turned-down": {
    "id": "event.turned-down",
    "url": "audio/event.turned-down.mp3",
    "text": "The up-card is turned down.",
    "status": "ready",
    "durationSeconds": 1.906939,
    "sha256": "a61a9025bdbfdcfbb8b416f33ba1460e9872eb4a58bc7a5c2245a0ebbbb2190a",
    "bytes": 30972
  },
  "call.clubs": {
    "id": "call.clubs",
    "url": "audio/call.clubs.mp3",
    "text": "calls clubs",
    "status": "ready",
    "durationSeconds": 1.306122,
    "sha256": "9833aab8b7f79f975857e00c25dba05bf20fade0ed509105b2c12d6561b05bf8",
    "bytes": 21358
  },
  "order.clubs": {
    "id": "order.clubs",
    "url": "audio/order.clubs.mp3",
    "text": "orders up clubs",
    "status": "ready",
    "durationSeconds": 1.123265,
    "sha256": "09cdec0813ac8358cd278fd55f83fc578863514d0c92b95dce20a18d892c2128",
    "bytes": 18433
  },
  "call.diamonds": {
    "id": "call.diamonds",
    "url": "audio/call.diamonds.mp3",
    "text": "calls diamonds",
    "status": "ready",
    "durationSeconds": 1.306122,
    "sha256": "380afc28bc46ce1e55a4b32d63b4d8bf349aa985caca6d0b9b5a09f285636d51",
    "bytes": 21358
  },
  "order.diamonds": {
    "id": "order.diamonds",
    "url": "audio/order.diamonds.mp3",
    "text": "orders up diamonds",
    "status": "ready",
    "durationSeconds": 1.123265,
    "sha256": "ed050d247abff2993aafa79b355eb6bec9c116e38f01010b4717327e9eaea4d8",
    "bytes": 18433
  },
  "call.hearts": {
    "id": "call.hearts",
    "url": "audio/call.hearts.mp3",
    "text": "calls hearts",
    "status": "ready",
    "durationSeconds": 1.201633,
    "sha256": "c5d9db8dbe8e103c612f83ae25976eb95ef3dc669dd983377a714e5d8ad0b238",
    "bytes": 19687
  },
  "order.hearts": {
    "id": "order.hearts",
    "url": "audio/order.hearts.mp3",
    "text": "orders up hearts",
    "status": "ready",
    "durationSeconds": 1.201633,
    "sha256": "95d572acc93915b30ffd930156f9aef29371577e86c4ab8478ee8bcbed786c19",
    "bytes": 19687
  },
  "call.spades": {
    "id": "call.spades",
    "url": "audio/call.spades.mp3",
    "text": "calls spades",
    "status": "ready",
    "durationSeconds": 1.149388,
    "sha256": "0236561c3bce06f908b057e40a058b8db103c2e3c5ae2af5ad3b8722e305b93d",
    "bytes": 18851
  },
  "order.spades": {
    "id": "order.spades",
    "url": "audio/order.spades.mp3",
    "text": "orders up spades",
    "status": "ready",
    "durationSeconds": 1.149388,
    "sha256": "818d7da2d10a563a37ab4288d3a484489419483fd7cd3e3fb49a67c073adee67",
    "bytes": 18851
  },
  "character.val-calls-hearts": {
    "id": "character.val-calls-hearts",
    "url": "audio/character.val-calls-hearts.mp3",
    "text": "Val calls hearts. Yeah, hearts. I knew that.",
    "status": "ready",
    "durationSeconds": 3.004082,
    "sha256": "7901e9c5d6935317a097c598edabb77388ec1a907c7a596867b161c83719cbaf",
    "bytes": 48526
  },
  "character.val-takes-trick": {
    "id": "character.val-takes-trick",
    "url": "audio/character.val-takes-trick.mp3",
    "text": "Val wins the trick. Totally saw that comin'.",
    "status": "ready",
    "durationSeconds": 2.586122,
    "sha256": "33205157c9d2f77a839cd65c8167dddda1d5606a84ef5cedab3cddb0497a2669",
    "bytes": 41838
  },
  "character.your-turn": {
    "id": "character.your-turn",
    "url": "audio/character.your-turn.mp3",
    "text": "Your turn. Do somethin' smart. I'll watch.",
    "status": "ready",
    "durationSeconds": 2.56,
    "sha256": "dcc4a5d6ce8687c7f097ce1999576cc5e7927b0830c1355980d5ede2f02853f0",
    "bytes": 41421
  },
  "character.west-plays-nine-hearts": {
    "id": "character.west-plays-nine-hearts",
    "url": "audio/character.west-plays-nine-hearts.mp3",
    "text": "West plays the nine of hearts. Okay, big shot.",
    "status": "ready",
    "durationSeconds": 3.004082,
    "sha256": "97cb9db5b98383e9af483522c76d0329ce74bcfe7dfa7d6bd10f5e2b4a71ce44",
    "bytes": 48526
  }
};
